Splashpage adjustments
AnthonyBronca/FireBnB pull request #272
Opened 2024-02-10 17:57 UTC by kryskimmel

- Incorporated infinite scrolling to splash page. After scrolling past 10 spot tiles, a fetch request to the api handling getting all of the spots would be made to load the next batch of 10 spot tiles. The number of spot tiles to fetch at a time can be adjusted
- Heart icon no longer flickers when pressed on and immediately switches colors between #FF385B and #535350. Functionality is still needed for the heart icon to add a spot to the user's wishlist
- Adjusted the alignment of splash page items by applying horizontal margins. Items should be fully visible when viewing the splash page on an iPhone 15
- Adjusted alignment of items in the Search component as the filter icon was clipped when splash page was viewed on an iPhone 15

2024-02-10 21:14 UTC, AnthonyBronca requested changes
Added some comments on possible things to look into before merging. Let me know if you want to go ahead with the merge though!

2024-02-10 21:14 UTC, AnthonyBronca commented on mobile/package.json
did we want to change the script to be "expo start -`-tunnel`"?
did we want to remove expo-splash-screen?
did we want to remove react-native-file-access?

2024-02-10 21:14 UTC, AnthonyBronca commented on mobile/screens/Home/Components/Spots.tsx
Did we want to move the fetch here out of redux? We could still incorporate the infinite scroll within the redux. We would just need the infinite scroll to call the redux dispatch function with an incrementing page state. If we fetch within the component like this, we may not have access to the redux store items we may need (although we may not need redux)

2024-02-13 22:55 UTC, kryskimmel commented on mobile/package.json
- [x] Change script to be "expo start --tunnel"
- [x] Remove expo-splash-screen
- [x] Remove react-native-file-access

2024-02-13 22:55 UTC, kryskimmel commented on mobile/screens/Home/Components/Spots.tsx
- [x] No longer fetching spots within component. Fetching is being done in /mobile/src/store/spots.ts using RTK Query.

2024-02-14 00:34 UTC, AnthonyBronca commented on mobile/screens/Home/Components/SearchModal.tsx
in a later push, we should probably aim to use "Image" from "expo-image" as it is faster and has caching. Although this should be fine for now!

2024-02-14 00:35 UTC, AnthonyBronca commented on mobile/store/spots.ts
On line 20, we have a type for this called Spots located in the redux.d.ts file. We should refactor that type in a later commit

2024-02-14 00:36 UTC, AnthonyBronca approved these changes

2024-02-14 00:36 UTC, merged

2024-02-14 01:18 UTC, kryskimmel reviewed
Comments have been reviewed and changes will be made in next PR.